name: Docker Build Runner

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          username: pi
          host: 99.98.11.100
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: BOT_TOKEN
          script:
            bash /home/pi/Bot_Data/charidiots/deploy.sh master
