name: Test Runner

on:
  push:
    branches: [ beta ]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - uses: actions/checkout@v3

      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: pi@99.98.11.100
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: touch ~/testSuccessful